# Generated by Django 3.2 on 2022-07-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=50)),
                ('descriptions', models.CharField(blank=True, max_length=250)),
                ('price', models.IntegerField()),
                ('sale', models.BooleanField()),
            ],
        ),
    ]
