# Generated by Django 3.2 on 2022-07-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20220718_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='garden_length',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='garden_width',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='quote',
            field=models.FloatField(default=5, editable=False),
            preserve_default=False,
        ),
    ]
