# Generated by Django 3.2 on 2022-07-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20220718_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.FloatField(editable=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='quote',
        ),
    ]
