# Generated by Django 3.2 on 2022-07-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20220718_2028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='quote',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='quote',
            field=models.FloatField(default=2, editable=False),
            preserve_default=False,
        ),
    ]
