# Generated by Django 3.2 on 2022-07-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20220718_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='quote',
            field=models.FloatField(),
        ),
    ]
