# Generated by Django 3.2 on 2022-07-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_userprofile_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='garden_length',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='garden_width',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='quote',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
