# Generated by Django 3.2 on 2022-07-26 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20220721_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='garden_length',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='garden_width',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='grass',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='irrigation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='quote',
        ),
    ]
