# Generated by Django 3.2 on 2022-07-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20220726_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='garden_length',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='garden_width',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='grass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='irrigation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='quote',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
