# Generated by Django 3.2 on 2022-08-21 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_userprofile_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phoneNumber',
            field=models.IntegerField(blank=True, null=True, verbose_name=django.core.validators.MaxValueValidator(999999999999)),
        ),
    ]
