# Generated by Django 3.2 on 2022-07-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sub_user_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garden_width', models.FloatField()),
                ('garden_length', models.FloatField()),
                ('irrigation', models.BooleanField()),
                ('grass', models.BooleanField()),
                ('first_line', models.CharField(max_length=75)),
                ('post_code', models.CharField(max_length=75)),
            ],
        ),
    ]
