# Generated by Django 3.2 on 2022-07-17 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_user_details',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.userprofile'),
        ),
    ]
