# Generated by Django 3.2 on 2022-07-19 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_user_details',
            old_name='quote',
            new_name='subscription_cost',
        ),
        migrations.RemoveField(
            model_name='sub_user_details',
            name='first_line',
        ),
        migrations.RemoveField(
            model_name='sub_user_details',
            name='garden_length',
        ),
        migrations.RemoveField(
            model_name='sub_user_details',
            name='garden_width',
        ),
        migrations.RemoveField(
            model_name='sub_user_details',
            name='grass',
        ),
        migrations.RemoveField(
            model_name='sub_user_details',
            name='irrigation',
        ),
        migrations.RemoveField(
            model_name='sub_user_details',
            name='post_code',
        ),
        migrations.AddField(
            model_name='sub_user_details',
            name='subscription_number',
            field=models.CharField(default=2, editable=False, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_user_details',
            name='user',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
