# Generated by Django 3.2 on 2022-07-18 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_user_details',
            name='first_line',
        ),
        migrations.RemoveField(
            model_name='sub_user_details',
            name='garden_length',
        ),
        migrations.RemoveField(
            model_name='sub_user_details',
            name='garden_width',
        ),
        migrations.RemoveField(
            model_name='sub_user_details',
            name='grass',
        ),
        migrations.RemoveField(
            model_name='sub_user_details',
            name='irrigation',
        ),
        migrations.RemoveField(
            model_name='sub_user_details',
            name='post_code',
        ),
        migrations.AddField(
            model_name='sub_user_details',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
