# Generated by Django 3.2 on 2022-07-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20220719_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_user_details',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
