# Generated by Django 3.2 on 2022-07-17 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('calculator', '0003_alter_sub_user_details_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_user_details',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile'),
        ),
    ]
