# Generated by Django 3.2 on 2022-07-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_sub_user_details_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_user_details',
            name='subscription_number',
            field=models.CharField(editable=False, max_length=32, unique=True),
        ),
    ]
