# Generated by Django 3.2 on 2022-07-17 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_alter_sub_user_details_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_user_details',
            name='first_line',
        ),
        migrations.RemoveField(
            model_name='sub_user_details',
            name='garden_length',
        ),
        migrations.RemoveField(
            model_name='sub_user_details',
            name='garden_width',
        ),
        migrations.RemoveField(
            model_name='sub_user_details',
            name='grass',
        ),
        migrations.RemoveField(
            model_name='sub_user_details',
            name='irrigation',
        ),
        migrations.RemoveField(
            model_name='sub_user_details',
            name='post_code',
        ),
    ]
