# Generated by Django 3.2 on 2022-07-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_alter_sub_user_details_subscription_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_user_details',
            name='address',
            field=models.CharField(default='Lemon house,Lemon Street,Lemon,LE MON', max_length=100),
        ),
    ]
