# Generated by Django 3.2 on 2022-07-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_sub_user_details_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_user_details',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
